# Generated by Django 4.2.7 on 2024-11-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name_plural": "Пользователи"},
        ),
        migrations.AddField(
            model_name="customuser",
            name="direction",
            field=models.CharField(
                choices=[
                    ("Back-End", "Back-End"),
                    ("Front-End", "Front-End"),
                    ("UX-UI", "UX-UI"),
                ],
                default=1,
                max_length=155,
                verbose_name="Направление",
            ),
            preserve_default=False,
        ),
    ]
