# Generated by Django 4.2.7 on 2024-11-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_options_customuser_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Back-End", "Back-End"),
                    ("Front-End", "Front-End"),
                    ("UX-UI", "UX-UI"),
                ],
                max_length=155,
                null=True,
                verbose_name="Направление",
            ),
        ),
    ]
