# Generated by Django 5.1.3 on 2024-11-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("Back-End", "Back-End"),
                            ("Front-End", "Front-End"),
                            ("UX-UI", "UX-UI"),
                            ("DEMO-DAY", "DEMO-DAY"),
                            ("Пробный-урок", "Пробный-урок"),
                            ("UX-UI", "UX-UI"),
                        ],
                        max_length=155,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "type_lesson",
                    models.CharField(max_length=155, verbose_name="Тип урока"),
                ),
                ("data", models.CharField(max_length=155, verbose_name="Начало урока")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=155,
                        verbose_name="Аудитория",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.CreateModel(
            name="Triallesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("Back-End", "Back-End"),
                            ("Front-End", "Front-End"),
                            ("UX-UI", "UX-UI"),
                            ("DEMO-DAY", "DEMO-DAY"),
                            ("Пробный-урок", "Пробный-урок"),
                            ("UX-UI", "UX-UI"),
                        ],
                        max_length=155,
                        verbose_name="Направление",
                    ),
                ),
                (
                    "invited",
                    models.CharField(max_length=155, verbose_name="Приглашено"),
                ),
                ("its_arrived", models.IntegerField(verbose_name="Пришло")),
                (
                    "total",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Общий пришло за последние 7 дней",
                    ),
                ),
                (
                    "lessons_last_week",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Уроков за последние 7 дней"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Недельный отчёт пробных уроков",
            },
        ),
    ]
