# Generated by Django 4.2.7 on 2024-11-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="audience",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                max_length=155,
                verbose_name="Aудитория",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="direction",
            field=models.CharField(
                choices=[
                    ("Back-End", "Back-End"),
                    ("Front-End", "Front-End"),
                    ("UX-UI", "UX-UI"),
                    ("DEMO-DAY", "DEMO-DAY"),
                    ("Пробный-урок", "Пробный-урок"),
                    ("UX-UI", "UX-UI"),
                ],
                max_length=155,
                verbose_name="Направление",
            ),
        ),
    ]
